name = "alokmail-bot"
main = "worker.js"
compatibility_date = "2024-09-01"

[vars]
BOT_TOKEN = "8943075720:AAHjufjd3Ll_AdvvqqeaN2n1d0FdNpyQSz0"
OWNER_ID = "8452322818"
DB_CHANNEL_ID = "-1004474665956"
DEFAULT_DOMAIN = "vibepulsemedia.online"
